version: '3.8'

services:
  database:
    build: docker/postgres
    volumes:
      - database:/var/lib/postgresql/data
      - ./docker/postgres/dumps/:/tmp/
    ports:
      - "5432:5432"
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    networks:
      - app-network
    restart: always
  backend:
    build: docker/backend
    volumes:
      - ./backend:/var/www/backend
    environment:
      - APP_NAME=${APP_NAME}
      - TZ=${TIMEZONE}
      - JWT_SECRET=${JWT_SECRET}
      - DATABASE_HOST=database
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - REDIRECT_URI=${REDIRECT_URI}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}
    networks:
      - app-network
    depends_on:
      - database
    restart: always
  frontend:
    build: docker/frontend
    volumes:
      - ./frontend:/var/www/frontend
    environment:
      - TZ=${TIMEZONE}
      - BASE_URL=${HOST}
      - CLIENT_ID=${CLIENT_ID}
      - REDIRECT_URI=${REDIRECT_URI}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}
    networks:
      - app-network
    depends_on:
      - backend
    restart: always
  nginx:
    build: docker/nginx
    ports:
      - "80:80"
      - "81:81"
    networks:
      - app-network
    restart: always

volumes:
  database:
    driver: local

networks:
  app-network:
    driver: bridge