version: '3.8'

services:
  backend:
    build: backend
    volumes:
      - ../backend:/var/www/backend
    networks:
      - app-network
  frontend:
    build: frontend
    volumes:
      - ../frontend:/var/www/frontend
    networks:
      - app-network
  nginx:
    build: nginx
    ports:
      - "80:80"
      - "81:81"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge