version: '3.8'

services:
  backend:
    build: backend
    volumes:
      - ../backend:/var/www/backend
    ports:
      - "3000:3000"
  frontend:
    build: frontend
    volumes:
      - ../frontend:/var/www/frontend
    ports:
      - "80:80"